### ISSUE TITLE
No such file or directory: 'data/SCONS_TL_SAMPLE01.txt'

### ISSUE THREAD

**Issue by zdavatz** [vdmitriyev/msconsconverter#1]
Thank you for this software. Something does not seem to be working here:

```
~/.software/msconsconverter> /usr/bin/python2.7 msconsconverter/msconsconverter.py ddata/ MSCONS_TL_SAMPLE01.txt,MSCONS_TL_SAMPLE02.txt --verbose
['SCONS_TL_SAMPLE01.txt', 'MSCONS_TL_SAMPLE02.tx']
[i] saving debugging info into file "logfile-20200507-1228-8b.log"
[i] class "MSCONSConverter" created
[i] processing file SCONS_TL_SAMPLE01.txt
[i] parsing MSCONS
Traceback (most recent call last):
  File "msconsconverter/msconsconverter.py", line 304, in <module>
    main(folder=input_folder, files=files)
  File "msconsconverter/msconsconverter.py", line 263, in main
    'VALUE'])
  File "msconsconverter/msconsconverter.py", line 201, in convert_to_csv
    mscons = self.parse_mscons(file_name)
  File "msconsconverter/msconsconverter.py", line 113, in parse_mscons
    read_file = open(file_name , "r")
IOError: [Errno 2] No such file or directory: 'data/SCONS_TL_SAMPLE01.txt'
```

**Comment by zdavatz** [comment]
I am on Linux, seems you are on Windows.

**Comment by zdavatz** [comment]
trying this now: https://github.com/notpeter/edicat

**Comment by vdmitriyev** [comment]
@zdavatz  Sorry, it looks I totally overlooked this issue. You are right, I tested this small script long time ago and used only Windows machine for that. Thanks for the link.

**Comment by vdmitriyev** [comment]
Thank you for the report. This bug was fixed https://github.com/vdmitriyev/msconsconverter/commit/6cd992190ce333fe22589e26289b9a8600febd76
